version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    environment:
      - TELEGRAM_TOKEN=your_telegram_token
      - OUTLINE_API_URL=your_outline_api_url
      - ADMIN_ID=your_admin_id
      - OUTLINE_USERS_GATEWAY=ssconf://bestvpn.world
      - OUTLINE_SALT=50842
      - CONN_NAME=RaphaelVPN
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=your_db_user
      - DB_PASSWORD=your_db_password
      - DB_NAME=your_db_name
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: