version: '3'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    env_file:                        # Указание .env файла
      - .env
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
