services:
  postgres:
    image: postgres:15
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  telegram-bot:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: unless-stopped