version: '3'

services:
  telegram-bot:
    depends_on:
      - postgres
    build: .
    container_name: telegram-bot
    env_file:                        # Указание .env файла
      - .env
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5434:5432
    env_file:
      - .env
    volumes:
      - /path/to/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
